### ISSUE TITLE
Typing with EEPROM.getKey is slow?

### ISSUE THREAD

**Issue by jamesnvc** [Lepidopterarium/Chrysalis#113]
Need to isolate & verify this, then probably report it to the Kaleidoscope-EEPROMKeymap repo.

**Comment by algernon** [comment]
This is strange, because it should *not* be slow. As in, even if EEPROM lookup is slower than from PROGMEM, it should not be noticably slower. Besides, we are caching the keymap, so under normal circumstances, you should not notice any difference at all.

I've been using an [EEPROM based keymap](https://github.com/algernon/Model01-sketch/blob/13411b0526a1de1af83faf178a468be7c9104f27/src/algernon.ino#L108-L116) for a good while now, and did not see this issue...

Very curious what the root cause for this is.

**Comment by jamesnvc** [comment]
It is completely possible it’s just something weird I’m doing on my end...maybe switching dynamically between reading keys from progmem and from eeprom defeats the caching or something?

**Comment by algernon** [comment]
No, it should not... I will try to reproduce the issue too. Having had a quick look at the code, I don't see why the slowdown may occur... though `.getKeyOverride` does do a lookup from EEPROM, and another from PROGMEM if the EEPROM has the key transparent. That still should not have a noticeable impact, however.
