### ISSUE TITLE
Some users might want to define a bunch of layers in Chrysalis and only sync some of them to their hardware

### ISSUE THREAD

**Issue by obra** [Lepidopterarium/Chrysalis#92]
Some users might want to keep a large layer library in Chrysalis and only upload a few of them to their keyboard at a time.

**Comment by Jennigma** [comment]
I expect I will be one of these, if a real world use case would help.  

I was doing some work in excel today thinking I could streamline my process by setting up special keys for common operations, but I don’t do this sort of thing in excel more than once every other month or so. I have a lot of infrequent specialized tasks that could be streamlined in this way. 

I’m thinking about using the butterfly key to access whatever special layer I have turned on at any given time, and to swap the layers out regularly to match my tasks. 

Thanks to you both for all you do. Working today after successfully beginning to customize my keyboard has been fun. Everything I do has me thinking, “how can I make this better by customizing my keyboard?” It is a new sense of freedom to be able to adapt my keyboard to me rather than vice versa. :-)

**Comment by heavenlyevil** [comment]
I would also want to do something similar to what Jennifer suggests
depending on what I'm working on/what programs I'm in. I also switch back
and forth between a 2006 MacBook Pro, 2016 Macbook, Windows 10 PC, and
Windows Server 2008 PC regularly so I'd want different layers depending on
the machine I'm working with as their programs/OSs differ quite a bit. I
would prefer to only store the layers I'd need in a given week/month on the
keyboard.

**Comment by jamesnvc** [comment]
The keymap editor now supports saving presets for layers, which should address this
